on:
  push:
    branches:
        - "Dev"
    paths:
        - ".github/workflows/devfiles/action.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build the Docker image
        run: docker build -t reactimage .
      
      - name: Tag the docker image
        run: docker tag reactimage:latest indumathicloud001/dev:latest

      - name: Docker Push
        run: docker push indumathicloud001/dev:latest
